### ISSUE TITLE
Update week-by-week: data-validation-with-python-and-regex too early

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/tech-department#140]
This is on week 4 but it's supposed to use the "string calculator" project instructions. Before peeps get that right they need:

- simple calc part 1 ( hello world of tdd)
- password checker (a more gentle introduction to regular expressions and error handling

Also thinking about it, the Password checker is probably a better "validation" project than the string calc. 

https://umuzi-org.github.io/tech-department/projects/tdd/password-checker/

**Comment by wgova** [comment]
- I will check the password checker and string calculator

- the website week by week plan is not yet up to date, but week 4 is the simple calculator in our schedule under curriculum changes
