### ISSUE TITLE
topic jasmine spies

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/tech-department#248]
#323 topic - jasmine spies

**Comment by Tsehla** [comment]
1) 
[ basically everything self-contained that acts like a black box to the outside world.] 
-> by outside world, you mean anything outside the program/code or do you refer to anything that is Ajax connection related. Pehaps you can add (.ie) to help new reader with quick clarification

2) [  - or even none at all, - or ]
-> do you meant to have those minus signs show like that?

3) [ McCoy ] who is maccoy, lol took me a while to get it, I would suggest [ as legit/real McCoy ] to cover learners like me.

4) [ let _age = 0,] underscore before variable is taken as if you have (underscoreJs), its fine in this case, but the dev community highly goes against it unless u got underscorejs as part of your code

5) [ describe or it block in ], perhaps you could like ('describe' or it 'block' in ), it helps
