### ISSUE TITLE
Add content rating / review google form to "what you need to know as a recruit" page

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/tech-department#252]
https://docs.google.com/forms/d/e/1FAIpQLSfHCI5JtVCo28Yrvjn2xUq3sWTyvFFAtvs0h3eaPEMHRGBr6Q/viewform?usp=sf_link

**Comment by Dibwe243** [comment]
![done](https://user-images.githubusercontent.com/34367821/69707073-b22aa480-1101-11ea-96ce-d9867b023622.png)
Looks like it was already done.
